url_recommendations = "https://api.spotify.com/v1/recommendations"
url_get_track = "https://api.spotify.com/v1/tracks/"
url_get_several_tracks = "https://api.spotify.com/v1/tracks"
url_audio_features_for_track = "https://api.spotify.com/v1/audio-features/"
url_audio_features_several_tracks = "https://api.spotify.com/v1/audio-features"
