url_recommendations = "https://api.spotify.com/v1/recommendations"
url_get_track = "https://api.spotify.com/v1/tracks/"
url_get_several_tracks = "https://api.spotify.com/v1/tracks"
url_audio_features_for_track = "https://api.spotify.com/v1/audio-features/"
url_audio_features_several_tracks = "https://api.spotify.com/v1/audio-features"
url_create_playlist = "https://api.spotify.com/v1/users/{user_id}/playlists"
url_add_items_to_playlist = "https://api.spotify.com/v1/playlists/{playlist_id}/tracks"
url_get_current_user_profile = "https://api.spotify.com/v1/me"
